package generator

const packageJsonTemplate = `{
	"name": "{{.Name}}",
	"version": "1.0.0",
	"description": "",
	"scripts": {
		"build:css": "npx @tailwindcss/cli -i ./web/static/css/input.css -o ./web/static/css/output.css --watch",
		"postinstall": "node -e \"require('fs').mkdirSync('web/static/js',{recursive:true}); require('fs').copyFileSync('node_modules/htmx.org/dist/htmx.min.js','web/static/js/htmx.min.js')\""
	},
	"devDependencies": {
		"@tailwindcss/cli": "latest",
		"daisyui": "latest",
		"htmx.org": "latest",
		"tailwindcss": "latest"
	}
}
`

const inputCssTemplate = `@import "tailwindcss";
@plugin "daisyui" {
  themes: light --default, dark --prefersdark, corporate, business, cupcake, retro, forest, night;
}
`

func (g *Generator) generateStatic() error {
	// Package.json for npm scripts (https://tailwindcss.com/docs/installation/tailwind-cli)
	if err := g.writeTemplate(g.projectPath("package.json"), packageJsonTemplate, g.config); err != nil {
		return err
	}

	// Input CSS - Tailwind v4 uses @import and @plugin (https://daisyui.com/docs/install/cli)
	if err := g.writeFile(g.projectPath("web/static/css/input.css"), inputCssTemplate); err != nil {
		return err
	}

	// Output CSS placeholder (generated by build:css)
	if err := g.writeFile(g.projectPath("web/static/css/output.css"), "/* Generated by Tailwind CSS - run: npm run build:css */"); err != nil {
		return err
	}

	return nil
}
